name = "substack-curator"
main = "dist/_worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[build]
command = "npm run build"

# Add your routes
routes = [
  { pattern = "papertrails.yourdomain.com", custom_domain = true }
]

# Optional: Add environment variables
[vars]
# MY_VAR = "value"