name: Fetch RSS Feeds (Staggered)

on:
  schedule:
    # Staggered batches during US early morning (off-peak) / India early morning
    # Batch 1: 2:00 AM UTC (10:00 PM EST, 7:30 AM IST)
    - cron: '0 2 * * *'
    # Batch 2: 3:00 AM UTC (11:00 PM EST, 8:30 AM IST)  
    - cron: '0 3 * * *'
    # Batch 3: 4:00 AM UTC (12:00 AM EST, 9:30 AM IST)
    - cron: '0 4 * * *'
    # Batch 4: 5:00 AM UTC (1:00 AM EST, 10:30 AM IST)
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      batch:
        description: 'Batch number (1-4)'
        required: true
        default: '1'
        type: choice
        options:
        - '1'
        - '2'
        - '3'
        - '4'

permissions:
  contents: write

jobs:
  determine-batch:
    runs-on: ubuntu-latest
    outputs:
      batch: ${{ steps.batch.outputs.batch }}
    steps:
      - name: Determine batch number
        id: batch
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "batch=${{ github.event.inputs.batch }}" >> $GITHUB_OUTPUT
          else
            # Determine batch based on current hour (UTC)
            hour=$(date -u +%H)
            case $hour in
              2) echo "batch=1" >> $GITHUB_OUTPUT ;;
              3) echo "batch=2" >> $GITHUB_OUTPUT ;;
              4) echo "batch=3" >> $GITHUB_OUTPUT ;;
              5) echo "batch=4" >> $GITHUB_OUTPUT ;;
              *) echo "batch=1" >> $GITHUB_OUTPUT ;;
            esac
          fi

  fetch-feeds:
    needs: determine-batch
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Fetch RSS feeds
        run: npm run fetch-feeds -- --batch=${{ needs.determine-batch.outputs.batch }} --total-batches=4
        
      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action - Batch ${{ needs.determine-batch.outputs.batch }}"
          git add data/articles.json data/articles-archive.json
          git diff --staged --quiet || git commit -m "Update RSS feeds batch ${{ needs.determine-batch.outputs.batch }} - $(date -u +"%Y-%m-%d %H:%M UTC")"
          git push