name: Fetch RSS Feeds with Proxy

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      use_proxy:
        description: 'Use Cloudflare proxy for Substack feeds'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  fetch-feeds:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hour timeout
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Fetch feeds with proxy
        env:
          WORKER_URL: ${{ secrets.WORKER_URL || 'https://papertrails.rabbitholes.garden' }}
          USE_PROXY: ${{ github.event.inputs.use_proxy || 'true' }}
        run: |
          echo "Starting feed fetch at $(date)"
          echo "Worker URL: ${WORKER_URL}"
          echo "Use proxy for Substack: ${USE_PROXY}"
          
          # Run the fetch script
          node src/scripts/fetch-feeds-with-proxy.js
          
          echo "Completed at $(date)"
      
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code data/articles.json || echo "changed=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push if changed
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add data/articles.json
          git commit -m "Update RSS articles [$(date -u '+%Y-%m-%d %H:%M:%S UTC')]
          
          Fetched via Cloudflare Worker proxy
          
          Co-Authored-By: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          
          git push
      
      - name: Upload fetch log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fetch-log-${{ github.run_id }}
          path: |
            logs/
            *.log
          retention-days: 7
      
      - name: Create issue if high failure rate
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const date = new Date().toISOString();
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `RSS Fetch Failed - ${date}`,
              body: `The RSS feed fetch workflow failed at ${date}.\n\nWorkflow run: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}\n\nThis might indicate:\n- Cloudflare Worker is down\n- Too many Substack feeds are blocking requests\n- Network issues\n\nPlease check the logs for details.`,
              labels: ['bug', 'automated']
            });